name: JF-CLI - Query Artifact properties
on:
# TURN-OFF on every push 
  push:
    branches: 
      - main
  issue_comment:
    types: [created]
  pull_request_target:
    types: [opened, synchronize]
permissions:
  actions: read # for detecting the Github Actions environment.
  id-token: write # for creating OIDC tokens for signing.
  packages: write # for uploading attestations.
  contents: read
  security-events: write # Required for uploading code scanning.
jobs:
  npmpackage:
    name: Queries
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    env:  
      JF_RT_URL: https://${{ vars.JF_NAME }}.jfrog.io
      JFROG_CLI_LOG_LEVEL: ${{vars.JFROG_CLI_LOG_LEVEL}} # DEBUG, INFO, WARN, ERROR
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20   # ref  https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idtimeout-minutes
    steps:
      # Use the specific setup-cli branch. Ref https://github.com/marketplace/actions/setup-jfrog-cli
      - name: Setup JFrog CLI
        uses: jfrog/setup-jfrog-cli@v4
        id: setup-cli
        env:
          JF_URL: ${{env.JF_RT_URL}}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          oidc-provider-name: ${{ vars.JF_OIDC_PROVIDER_NAME }}

      - name: Software version
        run: |
          # JFrog CLI version
          jf --version
          # Ping the server
          jf rt ping
          # NodeJS
          node -v
          npm -v
          # Java
          java -version
          # MVN
          mvn -version
          # Docker
          docker -v
          # Python
          python3 -V
          pip3 -V
          # jf config
          jf config show
          pwd

      - name: NPM - Query properties by '$QUERY_VAR'
        env:
          QUERY_VAR: "team=arch"
          FILE_NAME: "QueryByTeam.json"
          RT_REPO_VIRTUAL: 'krishnam-npm-virtual'
        run: |
          jf rt curl "/api/search/prop?repos=$RT_REPO_VIRTUAL&$QUERY_VAR" -o $FILE_NAME

          cat $FILE_NAME

          echo "# :frog: Query properties by 'team=arch' :mag:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          cat $FILE_NAME >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

      - name: NPM - Query properties by '$QUERY_VAR'
        env:
          QUERY_VAR: "team=arch&env=demo"
          FILE_NAME: "QueryByTeamEnv.json"
          RT_REPO_VIRTUAL: 'krishnam-npm-virtual'
        run: |
          jf rt curl "/api/search/prop?repos=$RT_REPO_VIRTUAL&$QUERY_VAR" -o $FILE_NAME
          cat $FILE_NAME

          echo "# :frog: Query property by '$QUERY_VAR' :mag:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          cat $FILE_NAME >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

      - name: NPM - Query properties by '$QUERY_VAR'
        env:
          QUERY_VAR: "build.name=spring-petclinic"
          FILE_NAME: "QueryByJavaBuildName.json"
          RT_REPO_VIRTUAL: 'krishnam-npm-virtual'
        run: |
          jf rt curl "/api/search/prop?repos=$RT_REPO_VIRTUAL&$QUERY_VAR" -o $FILE_NAME
          cat $FILE_NAME

          echo "# :frog: Query property by '$QUERY_VAR' :mag:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          cat $FILE_NAME >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

      - name: Gradle - Query properties by "$QUERY_VAR"
        env:
          QUERY_VAR: "build.name=spring-petclinic&build.id=ga-gdl-*"
          FILE_NAME: "QueryByMvnBuildNameAndBuildId.json"
          RT_REPO_VIRTUAL: 'krishnam-gradle-virtual'
        run: |
          jf rt curl "/api/search/prop?repos=$RT_REPO_VIRTUAL&$QUERY_VAR" -o $FILE_NAME
          cat $FILE_NAME

          echo "# :frog: Query property by '$QUERY_VAR' :mag:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          cat $FILE_NAME >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

      - name: MVN - Query properties by "$QUERY_VAR"
        env:
          QUERY_VAR: "build.name=spring-petclinic&build.id=ga-mvn-*"
          FILE_NAME: "QueryByMvnBuildNameAndBuildId.json"
          RT_REPO_VIRTUAL: 'krishnam-mvn-virtual'
        run: |
          jf rt curl "/api/search/prop?repos=$RT_REPO_VIRTUAL&$QUERY_VAR" -o $FILE_NAME
          cat $FILE_NAME

          echo "# :frog: Query property by '$QUERY_VAR' :mag:" >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY
          cat $FILE_NAME >> $GITHUB_STEP_SUMMARY
          echo " " >> $GITHUB_STEP_SUMMARY

      - name: Xray Query "$QUERY_VAR"
        env:
          QUERY_VAR: "build.name=spring-petclinic&build.id=ga-mvn-*"
          FILE_NAME: "QueryByMvnBuildNameAndBuildId.json"
          RT_REPO_VIRTUAL: 'krishnam-mvn-virtual'
        run: |
          jf xr curl 'api/v1/binMgr/{id}/builds'